#!/bin/bash
# merge_and_cleanup.sh - Worktree 머지 및 정리
#
# 인자:
#   $1 - 머지 타입 (squash, regular, rebase)
#   --delete-worktree  - Worktree 삭제 (선택)
#   --delete-branch    - 브랜치 삭제 (선택)
#
# 사용법:
#   bash merge_and_cleanup.sh squash
#   bash merge_and_cleanup.sh squash --delete-worktree --delete-branch

set -e

# 기본값
MERGE_TYPE=""
DELETE_WORKTREE=false
DELETE_BRANCH=false

# 인자 파싱
for arg in "$@"; do
    case "$arg" in
        squash|regular|rebase)
            MERGE_TYPE="$arg"
            ;;
        --delete-worktree)
            DELETE_WORKTREE=true
            ;;
        --delete-branch)
            DELETE_BRANCH=true
            ;;
        *)
            echo "알 수 없는 인자: $arg" >&2
            ;;
    esac
done

# 머지 타입 확인
if [ -z "$MERGE_TYPE" ]; then
    echo "사용법: $0 <squash|regular|rebase> [--delete-worktree] [--delete-branch]" >&2
    exit 1
fi

# Worktree인지 확인
if [ ! -f ".git" ]; then
    echo "오류: 현재 디렉토리는 Worktree가 아닙니다." >&2
    echo "Worktree 내부에서 실행해주세요." >&2
    exit 1
fi

# 현재 상태 확인
CURRENT_BRANCH=$(git branch --show-current)
CURRENT_DIR=$(pwd)
MAIN_DIR=$(git worktree list | head -1 | awk '{print $1}')
MAIN_BRANCH=$(cd "$MAIN_DIR" && git symbolic-ref --short HEAD 2>/dev/null || echo "main")

# 커밋되지 않은 변경사항 확인
UNCOMMITTED=$(git status --short | wc -l | tr -d ' ')
if [ "$UNCOMMITTED" -gt 0 ]; then
    echo "⚠️  커밋되지 않은 변경사항이 있습니다:" >&2
    git status --short >&2
    echo "" >&2
    echo "먼저 변경사항을 커밋하거나 스태시해주세요." >&2
    exit 1
fi

# 커밋 수 확인
COMMIT_COUNT=$(git log "$MAIN_BRANCH..HEAD" --oneline 2>/dev/null | wc -l | tr -d ' ')
if [ "$COMMIT_COUNT" -eq 0 ]; then
    echo "머지할 커밋이 없습니다." >&2
    exit 1
fi

echo "📝 머지 정보:"
echo "   현재 브랜치: $CURRENT_BRANCH"
echo "   대상 브랜치: $MAIN_BRANCH"
echo "   커밋 수: ${COMMIT_COUNT}개"
echo "   머지 타입: $MERGE_TYPE"
echo ""

# 메인 저장소로 이동
cd "$MAIN_DIR"

# 메인 브랜치 최신화
echo "메인 브랜치 최신화 중..." >&2
git checkout "$MAIN_BRANCH"
git pull --ff-only 2>/dev/null || true

# 머지 실행
echo "머지 실행 중..." >&2
case "$MERGE_TYPE" in
    squash)
        git merge --squash "$CURRENT_BRANCH"

        # 변경된 파일 분석
        CHANGED_FILES=$(git diff --cached --name-status | head -10)

        # 커밋 메시지 생성
        COMMIT_MSG="[${CURRENT_BRANCH#worktree/}] Squash merge

변경사항:
$(echo "$CHANGED_FILES" | awk '{print "- " $2 ": " $1}')

커밋 수: ${COMMIT_COUNT}개

🤖 Generated by Git Worktree Skill"

        git commit -m "$COMMIT_MSG"
        ;;
    regular)
        git merge "$CURRENT_BRANCH" --no-ff -m "Merge branch '$CURRENT_BRANCH'

🤖 Generated by Git Worktree Skill"
        ;;
    rebase)
        git rebase "$CURRENT_BRANCH"
        ;;
esac

echo "✅ 머지 완료!" >&2

# Worktree 삭제
if [ "$DELETE_WORKTREE" = true ]; then
    echo "Worktree 삭제 중..." >&2
    git worktree remove "$CURRENT_DIR" --force 2>/dev/null || {
        echo "⚠️  Worktree 자동 삭제 실패. 수동으로 삭제해주세요:" >&2
        echo "   git worktree remove $CURRENT_DIR" >&2
    }
fi

# 브랜치 삭제
if [ "$DELETE_BRANCH" = true ]; then
    echo "브랜치 삭제 중..." >&2
    git branch -d "$CURRENT_BRANCH" 2>/dev/null || {
        echo "⚠️  브랜치 자동 삭제 실패. 수동으로 삭제해주세요:" >&2
        echo "   git branch -d $CURRENT_BRANCH" >&2
    }
fi

# 결과 출력
echo ""
echo "✅ Worktree 머지 완료!"
echo ""
echo "📝 머지 정보:"
echo "   브랜치: $CURRENT_BRANCH"
echo "   머지 타입: $MERGE_TYPE"
echo "   커밋 수: ${COMMIT_COUNT}개"
echo ""
echo "🗑️ 정리:"
if [ "$DELETE_WORKTREE" = true ]; then
    echo "   Worktree 삭제: ✅"
else
    echo "   Worktree 삭제: ❌ (유지)"
fi
if [ "$DELETE_BRANCH" = true ]; then
    echo "   브랜치 삭제: ✅"
else
    echo "   브랜치 삭제: ❌ (유지)"
fi
echo ""
echo "⏭️ 다음 단계:"
echo "   1. 변경사항 확인: git log -1 --stat"
echo "   2. 원격 저장소에 푸시: git push"
